# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui6.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 976)
        MainWindow.setFixedSize(800, 976)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:#22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 131))
        self.frame.setStyleSheet("background-color:#fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(190, 30, 441, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.object = QtWidgets.QLineEdit(self.centralwidget)
        self.object.setGeometry(QtCore.QRect(390, 200, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.object.setFont(font)
        self.object.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.object.setText("")
        self.object.setAlignment(QtCore.Qt.AlignCenter)
        self.object.setObjectName("object")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 820, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:#fb5b5d;\n"
"    border-radius:30;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#fa4244\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.data = QtWidgets.QLineEdit(self.centralwidget)
        self.data.setGeometry(QtCore.QRect(390, 140, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.data.setFont(font)
        self.data.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.data.setText("")
        self.data.setAlignment(QtCore.Qt.AlignCenter)
        self.data.setObjectName("data")
        self.organization = QtWidgets.QLineEdit(self.centralwidget)
        self.organization.setGeometry(QtCore.QRect(390, 260, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.organization.setFont(font)
        self.organization.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.organization.setText("")
        self.organization.setAlignment(QtCore.Qt.AlignCenter)
        self.organization.setObjectName("organization")
        self.fio_insp = QtWidgets.QLineEdit(self.centralwidget)
        self.fio_insp.setGeometry(QtCore.QRect(390, 320, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fio_insp.setFont(font)
        self.fio_insp.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.fio_insp.setText("")
        self.fio_insp.setAlignment(QtCore.Qt.AlignCenter)
        self.fio_insp.setObjectName("fio_insp")
        self.violation = QtWidgets.QLineEdit(self.centralwidget)
        self.violation.setGeometry(QtCore.QRect(390, 380, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.violation.setFont(font)
        self.violation.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.violation.setText("")
        self.violation.setAlignment(QtCore.Qt.AlignCenter)
        self.violation.setObjectName("violation")
        self.fionar = QtWidgets.QLineEdit(self.centralwidget)
        self.fionar.setGeometry(QtCore.QRect(390, 440, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fionar.setFont(font)
        self.fionar.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.fionar.setText("")
        self.fionar.setAlignment(QtCore.Qt.AlignCenter)
        self.fionar.setObjectName("fionar")
        self.fiopro = QtWidgets.QLineEdit(self.centralwidget)
        self.fiopro.setGeometry(QtCore.QRect(390, 500, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fiopro.setFont(font)
        self.fiopro.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.fiopro.setText("")
        self.fiopro.setAlignment(QtCore.Qt.AlignCenter)
        self.fiopro.setObjectName("fiopro")
        self.fiodoc = QtWidgets.QLineEdit(self.centralwidget)
        self.fiodoc.setGeometry(QtCore.QRect(390, 560, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fiodoc.setFont(font)
        self.fiodoc.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.fiodoc.setText("")
        self.fiodoc.setAlignment(QtCore.Qt.AlignCenter)
        self.fiodoc.setObjectName("fiodoc")
        self.shirota = QtWidgets.QLineEdit(self.centralwidget)
        self.shirota.setGeometry(QtCore.QRect(390, 620, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.shirota.setFont(font)
        self.shirota.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.shirota.setText("")
        self.shirota.setAlignment(QtCore.Qt.AlignCenter)
        self.shirota.setObjectName("shirota")
        self.dolgota = QtWidgets.QLineEdit(self.centralwidget)
        self.dolgota.setGeometry(QtCore.QRect(390, 680, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dolgota.setFont(font)
        self.dolgota.setStyleSheet("background-color:#22222e;\n"
"border:2px solid #f66867;\n"
"border-radius:5;\n"
"color:white")
        self.dolgota.setText("")
        self.dolgota.setAlignment(QtCore.Qt.AlignCenter)
        self.dolgota.setObjectName("dolgota")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 260, 251, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setObjectName("label_4")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(130, 200, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(130, 140, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:white")
        self.label_13.setObjectName("label_13")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 320, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 380, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(130, 440, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(130, 560, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(130, 500, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(130, 620, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:white")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 680, 241, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white")
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 890, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:#fb5b5d;\n"
"    border-radius:30;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#fa4244\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 750, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    background-color:#fb5b5d;\n"
"    border-radius:30;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color:#fa4244\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ЗАПИСЬ ДАННЫХ В ТАБЛИЦУ"))
        self.pushButton_2.setText(_translate("MainWindow", "СОХРАНИТЬ ДАННЫЕ"))
        self.label_4.setText(_translate("MainWindow", "ОРГАНИЗАЦИЯ ИНСПЕКТОРА"))
        self.label_12.setText(_translate("MainWindow", "ОБЪЕКТ"))
        self.label_13.setText(_translate("MainWindow", "ДАТА И ВРЕМЯ"))
        self.label_5.setText(_translate("MainWindow", "ФИО ИНСПЕКТОРА"))
        self.label_6.setText(_translate("MainWindow", "НАРУШЕНИЕ"))
        self.label_7.setText(_translate("MainWindow", "ФИО НАРУШИТЕЛЯ"))
        self.label_8.setText(_translate("MainWindow", "ФИО ДОКЛАДЧИКА"))
        self.label_9.setText(_translate("MainWindow", "ФИО ПРОВЕРЯЮЩЕГО"))
        self.label_10.setText(_translate("MainWindow", "ШИРОТА МЕСТА"))
        self.label_11.setText(_translate("MainWindow", "ДОЛГОТА МЕСТА"))
        self.pushButton_3.setText(_translate("MainWindow", "ОЧИСТИТЬ"))
        self.pushButton_4.setText(_translate("MainWindow", "ЗАГРУЗИТЬ ФАЙЛ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
